name: epd_api_shelf
version: 0.0.1
description: A minimal web server using the shelf package.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: any
  jsonx: any
  quiver: '>=0.21.3 <0.22.0'
  shelf: any
dev_dependencies:
  mock: any
  unittest: any
