name: epd_api_shelf
version: 0.0.1
description: A minimal web server using the shelf package.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.13.0'
  intl: '>=0.12.1 <0.13.0'
  quiver:
  shelf: '>=0.5.6 <0.6.0'
  shelf_route: '>=0.11.0+1 <0.12.0'
  jsonx: ">=2.0.0 <3.0.0"
  rpc: ">=0.2.0 <0.3.0"
  logging: '>=0.9.3 <0.10.0'
  logging_handlers: ">=0.8.0 <0.9.0"
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  unittest: '>=0.11.5+4 <0.12.0'
