name: epd_api_shelf
version: 0.0.1
description: A minimal web server using the shelf package.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  html: any
  http: any
  http_server: any
  intl: any
  jsonx: any
  quiver: any
  rpc: any
  shelf: any
  shelf_route: any
dev_dependencies:
  mock: any
  unittest: any
dependency_overrides:
  quiver: '>=0.21.3'
